### PR TITLE
RHEL 5 compatibility

### PR DESCRIPTION
**Pull request by rouge8**
Fixes #107.

### CODE REVIEW

**Comment by johnzachary** [comment]
I'm not sure that `check` is required for building libcork in pnnl-amp (libcork is a submodule).  It's definitely required if your want to build libcork on its own.

**Comment by rouge8** [comment]
Okay, I'll remove that commit. Anything else? I managed to successfully build libcork using the [buzzy/build-centos32 Docker image](https://hub.docker.com/r/buzzy/build-centos32/~/dockerfile/).

**Comment by johnzachary** [comment]
Cool.  I managed to build it by hand also by making the changes you did (although I didn't commit the `long long` change.)  I think that and my patch to check for glibc version for `pthread_setname_np` were it.

**Comment by rouge8** [comment]
I've been able to build downstream packages using this, so I'm going to merge.

**Pull request merged**
